services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
    container_name: delta_miner
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/${USERNAME}/works
      - /home/${USERNAME}/works/node_modules
      - /home/${USERNAME}/works/.venv
